//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// このソース コードは xsd によって自動生成されました。Version=1.1.4322.2032 です。
// 
namespace Kodama.BootLoader.Schema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public class referenceAssembly {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("assembly", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public referenceAssemblyAssembly[] Items;
    }
    
    /// <remarks/>
    public class referenceAssemblyAssembly {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
}
